# Model comparision for change localization with two features
- Experiment 3 in Shin & Ma (2015-2)

In [11]:
import fnmatch # file name matching
import os
from scipy.io import loadmat

from pandas import DataFrame, Series
import pandas as pd
import scipy as sp
import numpy as np

import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
sns.set('poster')
sns.set_style('whitegrid')

import statsmodels.api as sm

from __future__ import division

pd.options.mode.chained_assignment = None

# 1. Data

In [65]:
# %load concat_matfiles.py
def concat_matfiles(exp_code,exp_ids,pathname,subject_names,exp_num=0):
    # Create a DataFrame from mat files by looping over subjects (subject_names)
    file_names = os.listdir(pathname)
    
    df = DataFrame()
    for exp_id in exp_ids:
        temp2 = DataFrame()
        for subject_name in subject_names:

            # Create a tag to find files based on a subject name
            if exp_num == 0:
                subject_tag = subject_name + str(exp_code) + '_' + str(exp_id) + '_'
            else:
                subject_tag = subject_name + str(exp_code) + '_' + str(exp_code) + '_' + str(exp_id) + '_'
            subject_files = fnmatch.filter(file_names, subject_tag + '*.mat') # Filter the files

            # Loop over filtered files
            temp1 = DataFrame()
            for subject_file in subject_files:

                # Convert a MATLAB matrix to a DataFrame
                temp0 = DataFrame(loadmat(pathname+subject_file)['datamatrix'])
                temp1 = pd.concat([temp1,temp0],ignore_index=True) # Concatenate DataFrames

            # Create a column to assign subject names
            temp1['Name'] = DataFrame([subject_name]*len(temp1))
            temp2 = pd.concat([temp2,temp1],ignore_index=True) # Concatenate

            # Create a column to assign experiment index
            if exp_code != 6 and exp_id == 1:
                feat_name = 'OriA'
            elif exp_code != 6 and exp_id == 2:
                feat_name = 'ColA'
            elif exp_id == 3:
                feat_name = 'OriC'
            elif exp_id == 4:
                feat_name = 'ColC'
            elif exp_id == 5:
                feat_name = 'OriD2'
            elif exp_id == 6:
                feat_name = 'ColD2'
            elif exp_code == 6 and exp_id == 1:
                feat_name = 'OriD1'
            elif exp_code == 6 and exp_id == 2:
                feat_name = 'ColD1'
            else:
                feat_name = 'B'                
            temp2['Feature'] = DataFrame([feat_name]*len(temp2))
                
        # Concatenate all subject data to create a single DataFrame            
        df = pd.concat([df,temp2],ignore_index=True)
    return df

In [66]:
def remap_colors(old_delta):
    if old_delta <= 180:
        new_delta = old_delta
    else:
        new_delta = 360 - old_delta
    new_delta = new_delta/2.0
    return new_delta

In [67]:
# Load data

pathnameD1 = 'one_change_lab/'
pathnameCD2 = 'two_feature_data/Exp3_all_change/' # this contains both Conditions A and D
subject_namesD1 = ['HJK','HS0','LLT','WK0','WZ0']
subject_namesCD2 = ['HJK','HS0','JSK','LLT','LN0','MBC','WK0','WZ0']

# there are only 3 subjects who did all experiments
common_subjects = set(subject_namesD1) & set(subject_namesCD2)
print common_subjects

set(['WK0', 'HS0', 'HJK', 'WZ0', 'LLT'])

In [118]:
exp_idsCD2 = [3,4,5,6] # 5: orientation + irrelevant color, 6: color + irrelevant orientation
exp_idsD1 = [1,2] # 1: orientation, 2: color
exp_codeCD2 = 3
exp_codeD1 = 6

# concatenating dataset
dfCD2 = concat_matfiles(exp_codeCD2,exp_idsCD2,pathnameCD2,common_subjects)
dfD1 = concat_matfiles(exp_codeD1,exp_idsD1,pathnameD1,common_subjects,exp_num=1)
df = pd.concat([dfCD2,dfD1],ignore_index=True)
df3 = df[['Name','Feature',1,2,8]]
df3.columns = ['Subject','Feature','Delta_Ori','Delta_Col','Correct']

df3.Delta_Col = df3.Delta_Col.apply((lambda x: remap_colors(x)))
df3.describe()

          Delta_Ori     Delta_Col       Correct
count  18000.000000  18000.000000  18000.000000
mean      -0.576351     30.277167      0.687500
std       42.391533     30.165285      0.463525
min      -90.000000      0.000000      0.000000
25%      -23.816156      0.000000      0.000000
50%        0.000000     23.000000      1.000000
75%       21.309192     57.000000      1.000000
max       90.000000     90.000000      1.000000

In [120]:
def label_bin(data,n_bins):
    bins = np.linspace(0,90,n_bins)
    inds = np.digitize(data, bins, right=True)
    return bins, inds

In [122]:
n_bins = 91
_, inds_ori = label_bin(abs(df3.Delta_Ori),n_bins)
_, inds_col = label_bin(df3.Delta_Col,n_bins)
df3['inds_ori'] = inds_ori
df3['inds_col'] = inds_col

In [124]:
df3.Feature.unique()

array(['OriC', 'ColC', 'OriD2', 'ColD2', 'OriD1', 'ColD1'], dtype=object)

In [125]:
df3.head()

  Subject Feature  Delta_Ori  Delta_Col  Correct  inds_ori  inds_col
0     WK0    OriC  44.874652          0        1        45         0
1     WK0    OriC -10.278552          0        1        11         0
2     WK0    OriC  54.401114          0        1        55         0
3     WK0    OriC -63.927577          0        1        64         0
4     WK0    OriC -46.880223          0        1        47         0

# 2. "Model 4"
- Orientation and color has its own independent resource.
- Entire resource is used to relevant information.
- A portion of resource is used to irrelevant information (ratio parameter).
- Each feature is independenlty encoded.
- In the decision-making step, an observer takes into account both relevant and irrelevant information.

In [315]:
from scipy.special import i0, i1
from scipy.interpolate import interp1d

# J to kappa conversion
upper_bound = 700
k_vec = np.linspace(0,upper_bound,10000)
J_vec = k_vec*i1(k_vec)/i0(k_vec)
f = interp1d(J_vec, k_vec) # kappa = f(J)

# encoding
def compute_ds(J_bar,tau,target,delta,n_change=1,rho=1,N=4):
    # J_bar = 0 is actually not possible because shape and scale parameters are defined in positive domain.
    # tau: scale parameter
    # target: target index
    # delta: change magnitude
    # n_change: number of objects changing
    Js = np.random.gamma(J_bar*rho/tau, tau, N*2)
    
    k1 = f(Js[:N])
    k2 = f(Js[N:])
    
    dL_noise = np.random.vonmises(0, k1)-np.random.vonmises(0, k2)

    if n_change == 1:
        dL_noise[target] = dL_noise[target] + delta
    else:
        dL_noise = dL_noise + delta
        
    k_denom = np.sqrt(k1**2 + k2**2 + 2*k1*k2*np.cos(dL_noise))
    d = i0(k1)*i0(k2)*np.exp(k1+k2-k_denom)/i0(k_denom)

    return d

In [316]:
def decide(d_rels,d_irrs):
    # decision making
    
    # d_rels: ds from relevant feature
    # d_irrs: ds from irrelevant feature
    # return 1 (correct) or 0 (incorrect)
    
    d = (d_rels+d_irrs)/2
    
    if sum(d==d.max()) > 1:
        max_indices = np.where(d==d.max())
        perft = int(np.random.randint(np.min(max_indices),np.max(max_indices)+1)==target)
    else:
        perf = int(d.argmax() == target)
    
    return perf

In [308]:
def get_p_logsum(conditions):
    p_logsum = 0
    for condition in conditions:
        
        if condition[0] == 'O':
            df = df_ori
        else:
            df = df_col
            
        p_corr_logsum = sum(np.log(df[condition][(df.Feature==condition) & (df.Correct==1)]))
        p_incorr_logsum = sum(np.log(df[condition][(df.Feature==condition) & (df.Correct==0)]))
        p_logsum += (p_corr_logsum+p_incorr_logsum)
        
    return p_logsum

In [313]:
def LLH(param_vec,df,sbjname,sampleSize):
    # compute model log likelihood (LLH) of Model 4
    # fit three conditions altogether: no-change, one-change, all-change
    # no change: essentially same as using only relevant information
    # data: pandas dataframe with all 3 conditions
    # sampleSize: MC samples
    
    Jbar1 = param_vec[0]
    tau1 = param_vec[1]
    Jbar2 = param_vec[2]
    tau2 = param_vec[3]
    rho1 = param_vec[4]
    rho2 = param_vec[5]
    
    deltas = np.linspace(0, 90, 91)
    target = 1 
    
    for delta in deltas:

        # Monte Carlo simulation
        perfs = []
        target_irrs = np.random.randint(0,4,sampleSize) # irrelevant target index
        for i in range(sampleSize):
            perfs.append({
                    'perf0_1': decide(compute_ds(Jbar1,tau1,target,delta),np.ones(4)),
                    'perf0_2': decide(compute_ds(Jbar2,tau2,target,delta),np.ones(4)),
                    'perf1_1': decide(compute_ds(Jbar1,tau1,target,delta),compute_ds(Jbar2*rho2,tau2,target_irrs[i],delta)),
                    'perf1_2': decide(compute_ds(Jbar2,tau2,target,delta),compute_ds(Jbar1*rho1,tau1,target_irrs[i],delta)),
                    'perf4_1': decide(compute_ds(Jbar1,tau1,target,delta),compute_ds(Jbar2*rho2,tau2,target,delta,n_change=4)),
                    'perf4_2': decide(compute_ds(Jbar2,tau2,target,delta),compute_ds(Jbar1*rho1,tau1,target,delta,n_change=4))
                })
        
        # compute mean
        perfs_delta.append(pd.DataFrame(perfs).mean().values) # probability of correct

    # row: delta, columns: perf types, values: p of correct
    df_p_corr = pd.DataFrame(perfs_delta)
    df_p_corr.columns = ['OriC', 'ColC', 'OriD1', 'ColD1', 'OriD2', 'ColD2']
    df_p_incorr = 1-df_p_corr

    # correct zeros to avoid log(0)
    df_p_corr[df_p_corr==0]= 1/(sampleSize*10)
    df_p_incorr[df_p_incorr==0]= 1/(sampleSize*10)    

    print df_p_corr
    
    # use merge to compute the p * trial efficiently (so here we create delta index)
    df_p_corr['inds_ori'] = np.linspace(0,90,91)
    df_p_corr['inds_col'] = np.linspace(0,90,91)

    # concatenate incorr mat
    df_p_incorr.columns = ['OriC_', 'ColC_', 'OriD1_', 'ColD1_', 'OriD2_', 'ColD2_']
    df_p = pd.concat([df_p_corr,df_p_incorr],axis=1)    
    
    # subject data
    data = df[df.Subject == sbjname]
    
    df_ori = data.merge(df_p,on=['inds_ori'],how='inner')
    df_col = data.merge(df_p,on=['inds_col'],how='inner')
    
    p_logsum = get_p_logsum(['OriC', 'ColC', 'OriD1', 'ColD1', 'OriD2', 'ColD2'])

In [314]:
param_vec = [10,20,5,2.5,.2,.3]
df = df3
sbjname = 'WK0'
sampleSize = 10
p_logsum = LLH(param_vec,df,sbjname,sampleSize)

      OriC   ColC  OriD1  ColD1  OriD2  ColD2
0    0.265  0.259  0.226  0.260  0.272  0.242
1    0.671  0.924  0.545  0.870  0.496  0.870
2    0.935  0.999  0.725  0.998  0.536  0.990
3    0.990  1.000  0.749  1.000  0.543  0.998
4    0.979  1.000  0.766  0.999  0.558  0.999
5    0.802  0.974  0.627  0.964  0.509  0.929
6    0.321  0.412  0.309  0.348  0.259  0.332
7    0.523  0.759  0.400  0.688  0.395  0.672
8    0.914  0.998  0.717  0.997  0.505  0.989
9    0.977  1.000  0.771  0.998  0.556  0.996
10   0.979  1.000  0.767  1.000  0.585  0.997
11   0.887  0.996  0.699  0.984  0.539  0.965
12   0.440  0.664  0.405  0.574  0.364  0.546
13   0.363  0.533  0.339  0.450  0.353  0.435
14   0.864  0.987  0.685  0.978  0.484  0.957
15   0.967  1.000  0.757  0.999  0.566  0.998
16   0.989  1.000  0.757  0.999  0.583  0.998
17   0.944  0.998  0.709  0.998  0.552  0.988
18   0.604  0.840  0.522  0.805  0.432  0.759
19   0.262  0.265  0.251  0.269  0.262  0.290
20   0.753  0.953  0.604  0.919  0.484  0.906
21   0.965  1.000  0.742  1.000  0.551  0.992
22   0.980  1.000  0.772  1.000  0.540  1.000
23   0.956  0.999  0.766  1.000  0.552  0.996
24   0.782  0.957  0.587  0.909  0.462  0.899
25   0.266  0.308  0.241  0.276  0.255  0.248
26   0.629  0.869  0.523  0.811  0.431  0.795
27   0.938  0.997  0.707  0.996  0.526  0.987
28   0.984  1.000  0.754  1.000  0.549  0.999
29   0.964  1.000  0.780  0.998  0.555  0.998
..     ...    ...    ...    ...    ...    ...
334  0.700  0.800  0.500  0.900  0.500  0.500
335  0.600  0.400  0.600  0.400  0.500  0.300
336  0.300  0.200  0.200  0.100  0.010  0.500
337  0.600  0.700  0.900  0.800  0.500  0.600
338  0.500  0.900  0.500  1.000  0.500  0.800
339  0.700  0.900  0.800  1.000  0.700  0.900
340  0.800  0.800  0.500  0.900  0.600  0.900
341  0.400  0.500  0.400  0.700  0.900  0.500
342  0.400  0.100  0.300  0.400  0.400  0.300
343  0.400  0.500  0.600  0.700  0.500  0.300
344  0.800  0.900  0.800  0.800  0.700  0.700
345  0.900  1.000  0.700  1.000  0.600  0.700
346  0.700  1.000  0.900  0.600  0.500  1.000
347  0.500  0.900  0.600  0.700  0.200  0.800
348  0.300  0.400  0.700  0.200  0.400  0.100
349  0.300  0.300  0.100  0.300  0.300  0.700
350  0.700  0.600  0.800  0.400  0.500  0.600
351  0.600  1.000  0.700  1.000  0.500  0.900
352  1.000  0.900  0.800  0.900  0.300  0.900
353  0.600  0.800  0.500  0.700  0.600  0.600
354  0.200  0.300  0.200  0.500  0.200  0.300
355  0.400  0.300  0.300  0.200  0.200  0.400
356  0.900  0.900  0.800  0.600  0.500  0.700
357  0.800  1.000  0.600  0.900  0.800  0.700
358  0.700  1.000  1.000  1.000  0.500  1.000
359  0.700  1.000  0.400  0.900  0.500  0.500
360  0.500  0.500  0.400  0.500  0.400  0.600
361  0.400  0.300  0.100  0.600  0.400  0.600
362  0.500  0.900  0.700  0.500  0.600  0.700
363  0.900  1.000  0.700  0.900  0.600  0.900

[364 rows x 6 columns]

ValueError: Length of values does not match length of index

In [278]:
Jbar1 = 10
Jbar2 = 20
target = 1
tau1 = 5
tau2 = 2.5
target_irr = 3
sampleSize = 1000
rho1 = 0.2
rho2 = 0.3
df = df3
sbjname = 'WK0'

deltas = np.linspace(0,90,91)
perfs_delta = []
for delta in deltas:
    
    perfs = []
    target_irrs = np.random.randint(0,4,sampleSize)
    for i in range(sampleSize):
        # here we fit three different conditions altogether: no-change, one-change, all-change
        # no change: essentially same as using only relevant information

        perfs.append({
                'perf0_1': decide(compute_ds(Jbar1,tau1,target,delta),np.ones(4)),
                'perf0_2': decide(compute_ds(Jbar2,tau2,target,delta),np.ones(4)),
                'perf1_1': decide(compute_ds(Jbar1,tau1,target,delta),compute_ds(Jbar2*rho2,tau2,target_irrs[i],delta)),
                'perf1_2': decide(compute_ds(Jbar2,tau2,target,delta),compute_ds(Jbar1*rho1,tau1,target_irrs[i],delta)),
                'perf4_1': decide(compute_ds(Jbar1,tau1,target,delta),compute_ds(Jbar2*rho2,tau2,target,delta,n_change=4)),
                'perf4_2': decide(compute_ds(Jbar2,tau2,target,delta),compute_ds(Jbar1*rho1,tau1,target,delta,n_change=4))
            })

    perfs_delta.append(pd.DataFrame(perfs).mean().values) # probability of correct
    
# row: delta, columns: perf types, values: p of correct
df_p_corr = pd.DataFrame(perfs_delta)
df_p_corr.columns = ['OriC', 'ColC', 'OriD1', 'ColD1', 'OriD2', 'ColD2']
df_p_incorr = 1-df_p_corr

# correct zeros to avoid log(0)
df_p_corr[df_p_corr==0]= 1/(sampleSize*10)
df_p_incorr[df_p_incorr==0]= 1/(sampleSize*10)

data = df[df.Subject == sbjname]

In [285]:
df_p_corr['inds_ori'] = np.linspace(0,90,91)
df_p_corr['inds_col'] = np.linspace(0,90,91)

# concatenate incorr mat
df_p_incorr.columns = ['OriC_', 'ColC_', 'OriD1_', 'ColD1_', 'OriD2_', 'ColD2_']
df_p = pd.concat([df_p_corr,df_p_incorr],axis=1)

In [287]:
df_p.head()

,OriC,ColC,OriD1,ColD1,OriD2,ColD2,inds_ori,inds_col,OriC_,ColC_,OriD1_,ColD1_,OriD2_,ColD2_
0,0.265,0.259,0.226,0.260,0.272,0.242,0,0,0.735,0.7410,0.774,0.7400,0.728,0.758
1,0.671,0.924,0.545,0.870,0.496,0.870,1,1,0.329,0.0760,0.455,0.1300,0.504,0.130
2,0.935,0.999,0.725,0.998,0.536,0.990,2,2,0.065,0.0010,0.275,0.0020,0.464,0.010
3,0.990,1.000,0.749,1.000,0.543,0.998,3,3,0.010,0.0001,0.251,0.0001,0.457,0.002
4,0.979,1.000,0.766,0.999,0.558,0.999,4,4,0.021,0.0001,0.234,0.0010,0.442,0.001

In [290]:
df_ori = data.merge(df_p,on=['inds_ori'],how='inner')
df_col = data.merge(df_p,on=['inds_col'],how='inner')

In [291]:
df_ori.head()

,Subject,Feature,Delta_Ori,Delta_Col,Correct,inds_ori,inds_col_x,OriC,ColC,OriD1,ColD1,OriD2,ColD2,inds_col_y,OriC_,ColC_,OriD1_,ColD1_,OriD2_,ColD2_
0,WK0,OriC,44.874652,0,1,45,0,0.688,0.912,0.569,0.865,0.461,0.858,45,0.312,0.088,0.431,0.135,0.539,0.142
1,WK0,OriC,-44.373259,0,1,45,0,0.688,0.912,0.569,0.865,0.461,0.858,45,0.312,0.088,0.431,0.135,0.539,0.142
2,WK0,OriC,44.874652,0,1,45,0,0.688,0.912,0.569,0.865,0.461,0.858,45,0.312,0.088,0.431,0.135,0.539,0.142
3,WK0,OriC,44.874652,0,1,45,0,0.688,0.912,0.569,0.865,0.461,0.858,45,0.312,0.088,0.431,0.135,0.539,0.142
4,WK0,OriC,44.874652,0,1,45,0,0.688,0.912,0.569,0.865,0.461,0.858,45,0.312,0.088,0.431,0.135,0.539,0.142

In [293]:
# OriC
print sum(np.log(df_ori.OriC[(df_ori.Feature=='OriC') & (df_ori.Correct==1)]))
print sum(np.log(df_ori.OriC_[(df_ori.Feature=='OriC') & (df_ori.Correct==0)]))

-155.662879088
-362.512567404

In [307]:
p_logsum = get_p_logsum(['OriC', 'ColC', 'OriD1', 'ColD1', 'OriD2', 'ColD2'])
print p_logsum

-1434.72209347

In [259]:
data_ori.head()

,Subject,Feature,Delta_Ori,Delta_Col,Correct,inds_ori,inds_col_x,OriC,ColC,OriD1,ColD1,OriD2,ColD2,inds_col_y
0,WK0,OriC,44.874652,0,1,45,0,0.713,0.929,0.577,0.874,0.459,0.866,45
1,WK0,OriC,-44.373259,0,1,45,0,0.713,0.929,0.577,0.874,0.459,0.866,45
2,WK0,OriC,44.874652,0,1,45,0,0.713,0.929,0.577,0.874,0.459,0.866,45
3,WK0,OriC,44.874652,0,1,45,0,0.713,0.929,0.577,0.874,0.459,0.866,45
4,WK0,OriC,44.874652,0,1,45,0,0.713,0.929,0.577,0.874,0.459,0.866,45

In [260]:
data_col.head()

,Subject,Feature,Delta_Ori,Delta_Col,Correct,inds_ori_x,inds_col,OriC,ColC,OriD1,ColD1,OriD2,ColD2,inds_ori_y
0,WK0,OriC,44.874652,0,1,45,0,0.237,0.262,0.252,0.243,0.256,0.246,0
1,WK0,OriC,-10.278552,0,1,11,0,0.237,0.262,0.252,0.243,0.256,0.246,0
2,WK0,OriC,54.401114,0,1,55,0,0.237,0.262,0.252,0.243,0.256,0.246,0
3,WK0,OriC,-63.927577,0,1,64,0,0.237,0.262,0.252,0.243,0.256,0.246,0
4,WK0,OriC,-46.880223,0,1,47,0,0.237,0.262,0.252,0.243,0.256,0.246,0

In [245]:
# subject data
gb_ori = data.groupby(('Feature','inds_ori'),as_index=False)
gb_col = data.groupby(('Feature','inds_col'),as_index=False)
           
corrs = gb.Correct.agg(np.sum)
corrs[corrs.Feature=='ColD1']
# 'OriC', 'ColC', 'OriD2', 'ColD2', 'OriD1', 'ColD1'

# print sum(gb_ori.get_group(('OriC',4)).Correct==1)
# print sum(gb_ori.get_group(('OriC',4)).Correct==0)

   Feature  inds_ori  Correct
1    ColD1         1       24
2    ColD1         2       23
3    ColD1         3       31
4    ColD1         4       20
5    ColD1         5       28
6    ColD1         6       27
7    ColD1         7       28
8    ColD1         8       27
9    ColD1         9       14
10   ColD1        10       27
11   ColD1        11       27
12   ColD1        12       24
13   ColD1        13       25
14   ColD1        14       17
15   ColD1        15       25
16   ColD1        16       21
17   ColD1        17       15
18   ColD1        18       27
19   ColD1        19       26
20   ColD1        20       26
21   ColD1        21       23
22   ColD1        22       28
23   ColD1        23       31
24   ColD1        24       16
25   ColD1        25       38
26   ColD1        26       26
27   ColD1        27       24
28   ColD1        28       25
29   ColD1        29       30
30   ColD1        30       31
..     ...       ...      ...
61   ColD1        61       19
62   ColD1        62       22
63   ColD1        63       26
64   ColD1        64       25
65   ColD1        65       26
66   ColD1        66       23
67   ColD1        67       30
68   ColD1        68       23
69   ColD1        69       27
70   ColD1        70       19
71   ColD1        71       24
72   ColD1        72       15
73   ColD1        73       28
74   ColD1        74       26
75   ColD1        75       21
76   ColD1        76       24
77   ColD1        77       22
78   ColD1        78       19
79   ColD1        79       22
80   ColD1        80       20
81   ColD1        81       22
82   ColD1        82       12
83   ColD1        83       21
84   ColD1        84       21
85   ColD1        85       22
86   ColD1        86       31
87   ColD1        87       23
88   ColD1        88       14
89   ColD1        89       18
90   ColD1        90       21

[90 rows x 3 columns]

In [200]:
gb = df3.groupby(('Feature','inds_ori'),as_index=False)

In [204]:
corrs = gb.Correct.agg(np.sum)
counts = gb.Correct.count()

In [213]:
corrs.Correct[corrs.Feature=='OriD1']
counts.Correct[counts.Feature=='OriD1']-corrs.Correct[corrs.Feature=='OriD1']

182    28
183    35
184    20
185    21
186    23
187    24
188    22
189    33
190    20
191    22
192    21
193    23
194    24
195    23
196    23
197    15
198    27
199    19
200    22
201    26
202    22
203    18
204    15
205    15
206    18
207    20
208     8
209    16
210     7
211     8
       ..
242     4
243     7
244     7
245     5
246     4
247     2
248     6
249     6
250     6
251     6
252     1
253     4
254     5
255     4
256     2
257     4
258     3
259     2
260     3
261     6
262     4
263     7
264     6
265     3
266     6
267     3
268     3
269     4
270     5
271     5
Name: Correct, dtype: float64

In [ ]:

p_log_like_corr_two1_4 = corr_trials_conj_ori.*log(p_corr_two1_4);
p_log_like_incorr_two1_4 = incorr_trials_conj_ori.*log(p_incorr_two1_4);
p_log_like_conj_ori = p_log_like_corr_two1_4 + p_log_like_incorr_two1_4;
p_incorr_two2_4 = 1-p_corr_two2_4;
p_corr_two2_4(p_corr_two2_4==0) = 1/(sampleSize*10);
p_incorr_two2_4(p_incorr_two2_4==0) = 1/(sampleSize*10);
p_log_like_corr_two2_4 = corr_trials_conj_col.*log(p_corr_two2_4);
p_log_like_incorr_two2_4 = incorr_trials_conj_col.*log(p_incorr_two2_4);
p_log_like_conj_col = p_log_like_corr_two2_4 + p_log_like_incorr_two2_4;
p_LLH_4 = sum(p_log_like_conj_ori(:)) + sum(p_log_like_conj_col(:));

In [ ]:
def model4_perf(condition,J_bar1,J_bar2,tau=10,samples=1000,rho=1.0):
    N = 4
    perfs_m4 = []
    deltas_rel = []
    targets = np.random.randint(0,N,samples)
    for sample in range(samples):
        target = targets[sample]
        delta_rel = np.pi/2*np.random.random()
        delta_irr = np.pi/2*np.random.random(N)

        d1 = compute_ds(J_bar1,tau,target,delta_rel,1)
        
        if condition == 'all-change':
            d2 = compute_ds(J_bar2*rho,tau,target,delta_irr,4)
        elif condition == 'one-change':
            target_irr = np.random.randint(0,N)
            d2 = compute_ds(J_bar2*rho,tau,target_irr,delta_irr[0],1)
        elif condition == 'no-change':
            d2 = compute_ds(J_bar2*rho,tau,target,0,4)
            
        d = (d1+d2)/2
        perf = int(d.argmax() == target)

        perfs_m4.append(perf)
        deltas_rel.append(delta_rel)
    df_m4 = pd.DataFrame({'delta':deltas_rel,'perf':perfs_m4})
    
    bins, inds = label_bin(abs(df_m4.delta),10)
    df_m4['inds'] = inds
    gb = df_m4.groupby(['inds'])
    m4_mean = gb.mean()